version: '1.0'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0123456789
      POSTGRES_DB: golang-backend-template
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - postgres-data:/var/lib/postgresql/data
      # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - APPNet
    ports:
      - "5432:5432"

  swagger-docs:
    image: swaggerapi/swagger-ui
    container_name: swagger-docs
    restart: on-failure
    volumes:
      - ./backend/docs/swagger.json:/docs/swagger.json
    environment:
      SWAGGER_JSON: /docs/swagger.json
    ports:
      - "6098:8080"
    networks:
      - APPNet
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - APPNet

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - APPNet
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    
  api:
    image: cosmtrek/air
    container_name: golang-backend-template-api
    restart: on-failure
    env_file: 
      - ./backend/.env
    ports:
      -  '8000:8000'
    volumes:
      - './backend:/golang-backend-template'
      - '~/.ssh/id_rsa:/root/.ssh/id_rsa'
      - '~/.ssh/known_hosts:/root/.ssh/known_hosts'
      - '~/.gitconfig:/root/.gitconfig'
      - './backend/docs:/golang-backend-template/docs'
    working_dir: '/golang-backend-template'
    networks:
      - APPNet
    depends_on:
      - postgres-db
  
  # web:
  #   image: node:18-alpine
  #   container_name: golang-backend-template-web
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - ./frontend/node_modules:/app/node_modules
  #   command: sh -c "npm install && npm run dev"
  #   networks:
  #     - APPNet
  #   depends_on:
  #     api: 
  #       condition: service_completed_successfully
networks:
  APPNet:
    driver: bridge

volumes:
  postgresql: